I have upgraded to php 8.2 with the tests running successfully
phpseclib/phpseclib pull request #1822
Opened 2022-07-19 09:14 UTC by CallMeJon90

I tried running tests on docker with php8.2 and there were some problems that I was able to solve.
These changes work on php8.1 but I have not tried on earlier versions.

2022-07-23 13:24 UTC, terrafrost requested changes
I tried to add 8.2 to .github/workflows/ci.yml but got an error. This is something that'll need to be figured out

2022-07-23 13:24 UTC, terrafrost commented on phpseclib/Math/PrimeField.php
> +    protected $modulo;
I think we can just delete `$this->modulo = $modulo;` from the constructor. Doesn't appear to be used anywhere else.

2022-07-23 13:33 UTC, jack-worman commented on phpseclib/Math/BigInteger/Engines/PHP/Reductions/EvalBarrett.php
> +                implode(',', array_map(self::class . '::float2string', $m)) . '];
https://php.watch/versions/8.2/partially-supported-callable-deprecation

2022-07-25 07:23 UTC, CallMeJon90 commented
Thank you for your responses.
Now I have an urgency to fix, as soon as possible I will continue to work on it.

2022-07-29 13:46 UTC, jack-worman commented on .github/workflows/ci.yml
> +                php-version: ['8.2']
Should still be testing on 8.1.
```suggestion
                php-version: ['8.1', '8.2']
```

2022-07-29 13:47 UTC, jack-worman commented on .github/workflows/ci.yml
> +                php-version: ['8.2']
And 8.2 should be marked as experimental

2022-07-29 14:17 UTC, CallMeJon90 commented
I don't see the error in getopt.php:38
I need to understand why

2022-07-29 14:21 UTC, Slamdunk commented
Composer SAT resolver installed the only set where PHP 8.2 is allowed, which is a really old one where all packaged didn't properly declared the php requirement in their `composer.json` files.

Deps on PHP 8.2 build need to be installed with `--ignore-platform-req=php` flag I think.

2022-07-29 14:24 UTC, Slamdunk commented
I suggest to add `--ignore-platform-req=php` on both builds until all CI is green, and only then edit the `ci.yml` to have `--ignore-platform-req=php` on PHP 8.2 only.

Github Actions YAML files may be very time consuming for newcomers: let's focus on the code first.

2022-07-30 01:21 UTC, jack-worman commented on phpseclib/Crypt/Common/SymmetricKey.php
> +
Merge error? These properties along with mcrypt were just removed.

2022-07-30 01:24 UTC, jack-worman commented on phpseclib/Crypt/DH/PublicKey.php
> +    protected $publicKey;
Looks like this should go on `DH` instead

2022-07-30 01:25 UTC, jack-worman commented on phpseclib/Crypt/DH/PublicKey.php
> +     * Public Key
No useless comments please

2022-07-30 01:32 UTC, jack-worman commented on phpseclib/Crypt/EC/BaseCurves/KoblitzPrime.php
> +     * @var array<array<string,BigInteger>>
```suggestion
     * @var list<array{a: BigInteger, b: BigInteger}>
```

2022-08-01 04:27 UTC, terrafrost reviewed
It's looking better!

The mcrypt stuff is weird but that's already been commented on.

Thanks for your work on this!

2022-08-02 07:25 UTC, Slamdunk commented on phpseclib/Crypt/Common/SymmetricKey.php
> +    private $hKey = null;
> I don't believe the `= null` is necessary

If `null` type is necessary for the variable, yes the initialization is necessary too: once typed attributes will land here, `private ?string $hKey;` cannot be checked without being initialized first, as it is currently used this way.

But as far as I can see, in the lazy-loading part an `isset()` check can be added first, so we can completely drop the `null` type requirement.

2022-08-13 21:53 UTC, merged